package com.bevietnam.ui.theme

import androidx.compose.ui.graphics.Color

val PrimaryRed = Color(0xFFC0392B)
val PrimaryRedLight = Color(0xFFE74C3C)
val Background = Color(0xFFFAF5E4)
val CardBackground = Color(0xFFFFFFFF)
val TextPrimary = Color(0xFF1A1A1A)
val TextSecondary = Color(0xFF6B6B6B)

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)
val md_theme_light_primary = Color(0xFF842C1A)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFA3432F)
val md_theme_light_onPrimaryContainer = Color(0xFFFFD3CA)
val md_theme_light_secondary = Color(0xFF605E56)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE3DFD5)
val md_theme_light_onSecondaryContainer = Color(0xFF64635A)
val md_theme_light_tertiary = Color(0xFF7B3411)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFF994B26)
val md_theme_light_onTertiaryContainer = Color(0xFFFFD4C3)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF93000A)
val md_theme_light_background = Color(0xFFFFF8F3)
val md_theme_light_onBackground = Color(0xFF1F1B15)
val md_theme_light_surface = Color(0xFFFFF8F3)
val md_theme_light_onSurface = Color(0xFF1F1B15)
val md_theme_light_surfaceVariant = Color(0xFFEAE1D7)
val md_theme_light_onSurfaceVariant = Color(0xFF56423E)
val md_theme_light_outline = Color(0xFF89726D)
val md_theme_light_inverseOnSurface = Color(0xFFF8EFE5)
val md_theme_light_inverseSurface = Color(0xFF343029)
val md_theme_light_inversePrimary = Color(0xFFFFB4A4)
val md_theme_light_surfaceTint = Color(0xFF9F402C)
val md_theme_light_outlineVariant = Color(0xFFDDC0BA)
val md_theme_light_scrim = Color(0xFF000000)
