#!/usr/bin/env bash
# Generate an nginx config from .env and run nginx as a path-router in front of
# the vLLM backends. cloudflared points at $ROUTER_PORT, so a single hostname
# serves all three models by URL path:
#
#   /v1/...         → text   backend ($TEXT_PORT)   [unchanged public URL]
#   /vision/v1/...  → vision backend ($VISION_PORT)
#   /embed/v1/...   → embed  backend ($EMBED_PORT)
#   /health         → text backend /health (tunnel liveness)
#
#   bash serve_router.sh
#
# Runs in the foreground (Ctrl+C stops the router; backends keep running).

set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT"

[[ -f "$ROOT/.env" ]] || { echo "[router] ERROR: .env not found." >&2; exit 1; }
set -a; source "$ROOT/.env"; set +a

command -v nginx >/dev/null 2>&1 || { echo "[router] ERROR: nginx not installed. Run bootstrap.sh." >&2; exit 1; }

BIND="${BIND_HOST:-127.0.0.1}"
RP="${ROUTER_PORT:-8000}"
CONF="$ROOT/nginx.conf"
mkdir -p "$ROOT/logs"

# Build the optional embed location only when embeddings are enabled.
EMBED_BLOCK=""
if [[ "${EMBED_ENABLED:-1}" == "1" ]]; then
  EMBED_BLOCK=$(cat <<EMBED
        location /embed/v1/ {
            rewrite ^/embed(/v1/.*)\$ \$1 break;
            proxy_pass http://127.0.0.1:${EMBED_PORT};
            proxy_set_header Host \$host;
            proxy_read_timeout 300s;
        }
EMBED
)
fi

echo "[router] writing $CONF"
cat > "$CONF" <<NGINX
# Generated by serve_router.sh — do not edit by hand (regenerated from .env).
worker_processes 1;
daemon off;
pid $ROOT/logs/nginx.pid;
error_log $ROOT/logs/nginx-error.log warn;
events { worker_connections 1024; }
http {
    access_log $ROOT/logs/nginx-access.log;
    # Captures can be large (multipart images proxied as base64 JSON).
    client_max_body_size 25m;
    proxy_http_version 1.1;

    server {
        listen ${BIND}:${RP};

        # text — public URL unchanged: https://$CF_HOSTNAME/v1/...
        location /v1/ {
            proxy_pass http://127.0.0.1:${TEXT_PORT};
            proxy_set_header Host \$host;
            proxy_read_timeout 300s;
        }

        # vision — https://$CF_HOSTNAME/vision/v1/...
        location /vision/v1/ {
            rewrite ^/vision(/v1/.*)\$ \$1 break;
            proxy_pass http://127.0.0.1:${VISION_PORT};
            proxy_set_header Host \$host;
            proxy_read_timeout 300s;
        }

${EMBED_BLOCK}

        # tunnel liveness
        location = /health {
            proxy_pass http://127.0.0.1:${TEXT_PORT}/health;
        }
    }
}
NGINX

nginx -t -c "$CONF" -p "$ROOT"
echo "[router] nginx listening on ${BIND}:${RP} → text:${TEXT_PORT} vision:${VISION_PORT}$([[ ${EMBED_ENABLED:-1} == 1 ]] && echo " embed:${EMBED_PORT}")"
exec nginx -c "$CONF" -p "$ROOT"
