#!/usr/bin/env bash
# Render VM .env files from one local-only secret file.
#
# Usage:
#   cp scripts/vm_secrets.env.example scripts/vm_secrets.env
#   $EDITOR scripts/vm_secrets.env
#   bash scripts/vm_apply_secrets.sh
#
# The real scripts/vm_secrets.env file is gitignored. Do not commit it.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SECRETS_FILE="${1:-$ROOT/scripts/vm_secrets.env}"

if [[ ! -f "$SECRETS_FILE" ]]; then
  echo "[vm-secrets] ERROR: $SECRETS_FILE not found" >&2
  echo "[vm-secrets] Create it from scripts/vm_secrets.env.example and fill your values." >&2
  exit 1
fi

python3 - "$ROOT" "$SECRETS_FILE" <<'PY'
import secrets
import sys
import re
from pathlib import Path
from urllib.parse import quote

root = Path(sys.argv[1])
secret_path = Path(sys.argv[2])


def parse_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    for line_number, raw in enumerate(path.read_text().splitlines(), start=1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            print(f"[vm-secrets] ignoring invalid line {line_number}: {line}")
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip()
        if not re.match(r"^[A-Za-z_][A-Za-z0-9_]*$", key):
            print(f"[vm-secrets] ignoring invalid key on line {line_number}: {key}")
            continue
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
            value = value[1:-1]
        values[key] = value
    return values


def get(values: dict[str, str], key: str, default: str = "") -> str:
    return values.get(key, default)


def generated(values: dict[str, str], key: str, nbytes: int = 24) -> str:
    value = values.get(key, "").strip()
    if value and value not in {"change-me", "your-secret-key"}:
        return value
    value = secrets.token_hex(nbytes)
    values[key] = value
    return value


def render_env(path: Path, lines: list[tuple[str, str] | str]) -> None:
    out: list[str] = []
    for item in lines:
        if isinstance(item, str):
            out.append(item)
        else:
            key, value = item
            out.append(f"{key}={value}")
    path.write_text("\n".join(out).rstrip() + "\n")
    path.chmod(0o600)


values = parse_env(secret_path)

postgres_db = get(values, "POSTGRES_DB", "bevietnam")
postgres_user = get(values, "POSTGRES_USER", "bevietnam")
postgres_host = get(values, "POSTGRES_HOST", "127.0.0.1")
postgres_port = get(values, "POSTGRES_PORT", "5432")
postgres_password = generated(values, "POSTGRES_PASSWORD", 18)
database_url = get(values, "DATABASE_URL")
if not database_url or "change-me" in database_url or "..." in database_url:
    database_url = (
        "postgresql+asyncpg://"
        f"{quote(postgres_user, safe='')}:{quote(postgres_password, safe='')}"
        f"@{postgres_host}:{postgres_port}/{quote(postgres_db, safe='')}"
    )

vllm_port = get(values, "VLLM_PORT", "8010")
vllm_host = get(values, "VLLM_HOST", "127.0.0.1")
root_vllm_base_url = get(values, "ROOT_VLLM_BASE_URL", f"http://127.0.0.1:{vllm_port}/v1")
vllm_served_name = get(values, "VLLM_SERVED_MODEL_NAME", "qwen2.5-14b-instruct")

secret_key = generated(values, "SECRET_KEY", 32)
hf_token = get(values, "HF_TOKEN")

root_env = [
    "# Generated by scripts/vm_apply_secrets.sh. Do not commit.",
    ("PROJECT_NAME", get(values, "PROJECT_NAME", "Tourism App API")),
    ("VERSION", get(values, "VERSION", "0.1.0")),
    ("AI_CORE_BASE_URL", get(values, "AI_CORE_BASE_URL", "http://localhost:8001")),
    ("AI_CORE_TIMEOUT", get(values, "AI_CORE_TIMEOUT", "300")),
    ("AI_CORE_USE_MOCK", get(values, "AI_CORE_USE_MOCK", "false")),
    ("QUESTION_POOL_PATH", get(values, "QUESTION_POOL_PATH", "data/question_pool.json")),
    "",
    ("GOONG_API_KEY", get(values, "GOONG_API_KEY")),
    ("GOONG_BASE_URL", get(values, "GOONG_BASE_URL", "https://rsapi.goong.io")),
    ("GOONG_TIMEOUT", get(values, "GOONG_TIMEOUT", "10")),
    ("OPENWEATHER_API_KEY", get(values, "OPENWEATHER_API_KEY")),
    ("OPENWEATHER_BASE_URL", get(values, "OPENWEATHER_BASE_URL", "https://api.openweathermap.org/data/2.5")),
    ("OPENWEATHER_TIMEOUT", get(values, "OPENWEATHER_TIMEOUT", "10")),
    "",
    ("DATABASE_URL", database_url),
    ("AUTO_POSTGRES", get(values, "AUTO_POSTGRES", "1")),
    ("POSTGRES_DB", postgres_db),
    ("POSTGRES_USER", postgres_user),
    ("POSTGRES_PASSWORD", postgres_password),
    ("POSTGRES_HOST", postgres_host),
    ("POSTGRES_PORT", postgres_port),
    "",
    ("SECRET_KEY", secret_key),
    ("ALGORITHM", get(values, "ALGORITHM", "HS256")),
    ("ACCESS_TOKEN_EXPIRE_MINUTES", get(values, "ACCESS_TOKEN_EXPIRE_MINUTES", "10080")),
    "",
    ("GEMINI_API_KEY", get(values, "GEMINI_API_KEY")),
    ("LLM_PROVIDER", get(values, "LLM_PROVIDER", "vllm")),
    ("VLLM_BASE_URL", root_vllm_base_url),
    ("VLLM_MODEL", get(values, "ROOT_VLLM_MODEL", vllm_served_name)),
    ("VLLM_API_KEY", get(values, "VLLM_API_KEY")),
    ("VLLM_VISION_BASE_URL", get(values, "VLLM_VISION_BASE_URL", "https://api.iamphuckhang.dev/vision/v1")),
    ("VLLM_VISION_MODEL", get(values, "VLLM_VISION_MODEL", "qwen2.5-vl-7b")),
    "",
    ("HF_TOKEN", hf_token),
    ("QDRANT_HOST", get(values, "QDRANT_HOST", "localhost")),
    ("QDRANT_PORT", get(values, "QDRANT_PORT", "6333")),
    ("QDRANT_PATH", get(values, "QDRANT_PATH", "/tmp/bevietnam-qdrant")),
    ("QDRANT_CLUSTER_ENDPOINT", get(values, "QDRANT_CLUSTER_ENDPOINT")),
    ("QDRANT_API_KEY", get(values, "QDRANT_API_KEY")),
    ("QDRANT_COLLECTION", get(values, "QDRANT_COLLECTION", "cultural_knowledge")),
    "",
    ("LANGSMITH_TRACING", get(values, "LANGSMITH_TRACING", "false")),
    ("LANGSMITH_API_KEY", get(values, "LANGSMITH_API_KEY")),
    ("LANGSMITH_PROJECT", get(values, "LANGSMITH_PROJECT", "BeVietnam")),
    "",
    ("BACKEND_HOST", get(values, "BACKEND_HOST", "0.0.0.0")),
    ("BACKEND_PORT", get(values, "BACKEND_PORT", "8000")),
    ("AI_HOST", get(values, "AI_HOST", "0.0.0.0")),
    ("AI_PORT", get(values, "AI_PORT", "8001")),
    ("RUN_MIGRATIONS", get(values, "RUN_MIGRATIONS", "1")),
    ("INSTALL_DEPS", get(values, "INSTALL_DEPS", "auto")),
    ("AUTO_APT_INSTALL", get(values, "AUTO_APT_INSTALL", "1")),
    ("START_VLLM", get(values, "START_VLLM", "1")),
    ("START_VLLM_TUNNEL", get(values, "START_VLLM_TUNNEL", "1")),
]

vllm_env = [
    "# Generated by scripts/vm_apply_secrets.sh. Do not commit.",
    ("VLLM_MODEL", get(values, "VLLM_MODEL", "Qwen/Qwen2.5-14B-Instruct")),
    ("VLLM_SERVED_MODEL_NAME", vllm_served_name),
    ("VLLM_DTYPE", get(values, "VLLM_DTYPE", "bfloat16")),
    ("VLLM_MAX_MODEL_LEN", get(values, "VLLM_MAX_MODEL_LEN", "16384")),
    ("VLLM_GPU_MEMORY_UTILIZATION", get(values, "VLLM_GPU_MEMORY_UTILIZATION", "0.92")),
    ("VLLM_ENABLE_PREFIX_CACHING", get(values, "VLLM_ENABLE_PREFIX_CACHING", "1")),
    "",
    ("VLLM_HOST", vllm_host),
    ("VLLM_PORT", vllm_port),
    ("VLLM_API_KEY", get(values, "VLLM_API_KEY")),
    ("VLLM_VERSION", get(values, "VLLM_VERSION", "0.8.5")),
    "",
    ("HF_TOKEN", hf_token),
    "",
    ("CF_HOSTNAME", get(values, "CF_HOSTNAME", "api.iamphuckhang.dev")),
    ("CF_TUNNEL_ID", get(values, "CF_TUNNEL_ID")),
    ("CF_ACCOUNT_TAG", get(values, "CF_ACCOUNT_TAG")),
    ("CF_TUNNEL_SECRET", get(values, "CF_TUNNEL_SECRET")),
]

render_env(root / ".env", root_env)
render_env(root / "vllm_hosting" / ".env", vllm_env)
secret_path.chmod(0o600)

print(f"[vm-secrets] wrote {root / '.env'}")
print(f"[vm-secrets] wrote {root / 'vllm_hosting' / '.env'}")
print("[vm-secrets] secret values were not printed")
PY
